{
 "title": "GKE Prometheus Pod/Node Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GKE Prometheus Pod/Node Monitoring Test",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has example charts for metrics exported by Prometheus, for example metrics from [Kubernetes Pods](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) and [Kubernetes Nodes](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/cluster/node-metrics.md).\n\nNote that if you are using the deprecated [Stackdriver Prometheus sidecar](https://cloud.google.com/monitoring/api/metrics_other#prometheus) then this dashboard will not function as expected. This dashboard requires metrics to be collected by Google Managed Prometheus as they will then be exposed under the `prometheus.googleapis.com` metrics descriptor.\n\nIf you are using a GKE cluster that has been configured to automatically scrape Kube state metrics then some of the panels on this dashboard will not show data as the default configuration only sends a [subset](https://cloud.google.com/kubernetes-engine/docs/how-to/kube-state-metrics) of the available Kube state metrics.\n\nTo retrieve all available Kube state metrics [this](https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/kube_state_metrics#install-exporter) documentation can be followed."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "kube_pod_status_phase [SUM]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "aliasBy": "{{metric.label.phase}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_pod_status_phase/gauge"
      ],
      "groupBys": [ "metric.label.phase" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "kube_pod_status_ready [SUM]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "aliasBy": "{{resource.label.namespace}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_pod_container_status_ready/gauge"
      ],
      "groupBys": [ "resource.label.namespace" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "kube_pod_container_status_running [SUM]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "aliasBy": "{{resource.label.namespace}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_pod_container_status_running/gauge"
      ],
      "groupBys": [ "resource.label.namespace" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "kube_node_status_condition [SUM]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "aliasBy": "{{metric.label.condition}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_node_status_condition/gauge"
      ],
      "groupBys": [ "metric.label.condition" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "kube_node_status_capacity_pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "aliasBy": "{{metric.label.node}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.unit",
       "=",
       "integer",
       "AND",
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_node_status_capacity/gauge"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "kube_node_status_allocatable_pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "aliasBy": "{{metric.label.node}}",
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "metric.label.unit",
       "=",
       "integer",
       "AND",
       "metric.type",
       "=",
       "prometheus.googleapis.com/kube_node_status_allocatable/gauge"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project"
     }
    }
   ]
  }
 ]
}